### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by Zarkonnen** [SeleniumBuilder/se-builder#229]
Travis CI always fails on commits, eg: https://travis-ci.org/sebuilder/se-builder/builds/40042951

Appears to be some npm problem.

**Comment by fat-troll** [comment]
It seems like you have npm version which doesn't support "^version" notation:
```
npm ERR! Error: No compatible version found: assert-plus@'^0.1.5'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:c
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 2.6.32-042stab094.7
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/sebuilder/se-builder
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30

```
In that way it's better to change from "^version" to ">=version" OR if you can't just make a small hack for npm in your travis config, adding:
```
before_install:
  - npm install -g 'npm@>=1.3.7'
```

It should also fix some other errors, if you are building it clearly (in a "clean" workspace)
```
Error: ENOENT, lstat
```
